#ifndef INTERFACE_LIST_H
#define INTERFACE_LIST_H

namespace BUTTON_ID { enum { NONE, OK, BACK, SINGLE_PLAYER, ONLINE_MENU, HOST_GAME, JOIN_GAME, START_GAME, LEAVE_GAME, DISCONNECT, MAP_EDITOR, ADD_BOT, REMOVE_BOT, READY, SELECT_MAP, SELECT_MAP_WINDOW, OPTIONS, HELP_SCREEN, EXIT,
EDITOR_NEW_MAP, EDITOR_SAVE_MAP_WINDOW, EDITOR_SAVE_MAP, EDITOR_SAVE_MAP_ASK, EDITOR_MAP_PROPERTIES_WINDOW, EDITOR_RESIZE_MAP_WINDOW, EDITOR_APPLY_MAP_RESIZE, EDITOR_CHANGE_MODE, EDITOR_TYPE_ID, EDITOR_PLAYER_ID, EDITOR_PREV_PAGE, EDITOR_NEXT_PAGE }; }
namespace WINDOW_ID { enum { NONE, INFO, MAIN_MENU, ONLINE, GAME_SETUP, SELECT_MAP, SAVE_MAP, OPTIONS, SERVER_NOT_RESPONDING, INGAME_ESC, EDITOR_NEW_MAP, EDITOR_RESIZE_MAP,  COUNT}; }

#endif
