#ifndef LISTS_H
#define LISTS_H

#define DEFAULT_SCREEN_W 1280
#define DEFAULT_SCREEN_H 720

#define TILE_SIZE 32
//#define WALK_SPEED 2.0f

#define GAME_CAMERA_SPEED 8.0f

//#define MAP_WIDTH 30
//#define MAP_HEIGHT 30

#define ANT_ANIMATION_FRAMES 2
#define GRAVITY_FORCE 1.0f

#define ANTHILL_RADIUS (TILE_SIZE * 1.5f)
#define ANT_RADIUS (TILE_SIZE * 0.4f)

//#define FIRE_TOTAL_ANIMATION_FRAMES 8
#define FLAG_TOTAL_ANIMATION_FRAMES 3


#define MAX_PLAYERS 4
#define MAX_ANTS 255
#define MAX_POWERUPS 1024
#define MAX_FOOD 1024

#define MAP_DIMENSION_LIMIT 1024

#define DEFAULT_SERVER_PORT 1254

#define GAMECODE 5847923

#define SERVER_CONNECTION_ID -1
#define BOT_CONNECTION_ID -2
#define NO_PLAYER_CONNECTION_ID -3

//#define GAME_VERSION 1
#define VERSION_STRING "1.0.0"

namespace GAMESTATE { enum { EXIT, MENU, PLAYING }; }

namespace TILE { enum { DIRT, SAND, ROCKY_GROUND, MUD, WATER, _VOID_, COUNT }; } 
namespace SECONDARY_TILE { enum { NONE, FIRE, MUD_BRIDGE, LANDMINE_0 }; } 
namespace EDITOR_ELEMENT { enum { TERRAIN, TERRAIN_OBJECT, ANTHILL, ANT, POWERUP, FOOD, OBSTACLE, POWERUP_GENERATOR }; } 

namespace CONTROLLER { enum { LOCAL, AI, REMOTE, REMOTE_AI, COUNT }; } 

#endif
