#ifndef NET_COMMANDS_LIST_H
#define NET_COMMANDS_LIST_H

namespace OP { enum { NONE, JOINING, ADD_PLAYER, PLAYER_DISCONNECTION, CHAT_MESSAGE, GAME_START, UPDATE, RESYNC, MAP_CHANGE, RULE_UPDATE, COLOR_CHANGE, READY_TICK, /* ANT_MOVE, ANT_ATTACK, ANT_ABILITY, EGG_HATCH,*/ COUNT }; }

namespace DISCONNECTION { enum { NORMAL, SERVER_CLOSING, KICKED, INCORRECT_PASSWORD, SERVER_IS_FULL, GAME_ALREADY_STARTED, INCORRECT_VERSION, LOGIN_ERROR, ALREADY_IN }; }

#endif
